// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGu3Fu1DyGOPSr1ioLjDIsA4lY3YZurFg',
    appId: '1:367908416154:web:fab3f78d93623e1b628d23',
    messagingSenderId: '367908416154',
    projectId: 'kigali-city-directory-a10cd',
    authDomain: 'kigali-city-directory-a10cd.firebaseapp.com',
    storageBucket: 'kigali-city-directory-a10cd.firebasestorage.app',
    measurementId: 'G-D9WXK2V49W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmxQ4mo7fvvXfoN1fXwT3yziOpuEKA5ak',
    appId: '1:367908416154:android:b6e98e8db3852a9b628d23',
    messagingSenderId: '367908416154',
    projectId: 'kigali-city-directory-a10cd',
    storageBucket: 'kigali-city-directory-a10cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVkj2Imwgr27xdK-oFuLiNYCyOg4CQ5jw',
    appId: '1:367908416154:ios:ebd3b4dbc03d471d628d23',
    messagingSenderId: '367908416154',
    projectId: 'kigali-city-directory-a10cd',
    storageBucket: 'kigali-city-directory-a10cd.firebasestorage.app',
    iosBundleId: 'com.example.cityMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVkj2Imwgr27xdK-oFuLiNYCyOg4CQ5jw',
    appId: '1:367908416154:ios:ebd3b4dbc03d471d628d23',
    messagingSenderId: '367908416154',
    projectId: 'kigali-city-directory-a10cd',
    storageBucket: 'kigali-city-directory-a10cd.firebasestorage.app',
    iosBundleId: 'com.example.cityMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGu3Fu1DyGOPSr1ioLjDIsA4lY3YZurFg',
    appId: '1:367908416154:web:75df7225e599af08628d23',
    messagingSenderId: '367908416154',
    projectId: 'kigali-city-directory-a10cd',
    authDomain: 'kigali-city-directory-a10cd.firebaseapp.com',
    storageBucket: 'kigali-city-directory-a10cd.firebasestorage.app',
    measurementId: 'G-T2G8JM3MGC',
  );
}
